services:
  neo4j:
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    expose:
      - 7687
    environment:
      - NEO4J_AUTH=neo4j/changeme
    volumes:
      - type: bind
        source: ./localdb/data
        target: /data
      - type: bind
        source: ./localdb/logs
        target: /logs
    image: neo4j:5.6.0