version: '3.8'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.6.0
  
  matts:
    container_name: matts
    image: ghcr.io/m-flak/matts
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - neo4j
    links:
      - neo4j
