CREATE CONSTRAINT IF NOT EXISTS FOR(a:Applicant) REQUIRE a.uuid IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR(j:Job) REQUIRE j.uuid IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR(e:Employer) REQUIRE e.uuid IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR(u:User) REQUIRE u.userName IS UNIQUE;
